name: webworker.tech
appid: owt9b9
invokeUrl: https://owt9b9.laf.run
function:
  debugTokenExpire: 1690390636
storage:
  endpoint: https://oss.laf.run
  accessKeyId: 3UF0L2N659Q6J1KZUG16
  accessKeySecret: hJUFo+LJ2nlU58YGp819Jc7bM1JFr2Ld1h7gNQhX
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIzVUYwTDJONjU5UTZKMUtaVUcxNiIsImV4cCI6MTY5MDM5MDYzNiwicGFyZW50Ijoib3d0OWI5Iiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.ILEwatHTGiHv5Yum06PQM9MVy0dx-qFf7CMo_gSQjXRdaDmGbsrrV4YlEGNKvkVpim0vCPEuovZz5DcMdMX5dA
  expire: 1690390636
