/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TSpace: typeof import('tdesign-vue-next')['Space']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
